/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIScreenShot */

#ifndef _Included_JNIScreenShot
#define _Included_JNIScreenShot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIScreenShot
 * Method:    captureScreen
 * Signature: (Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_JNIScreenShot_captureScreen
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     JNIScreenShot
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNIScreenShot_getNumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
