/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JNIScreenShotTest */

#ifndef _Included_JNIScreenShotTest
#define _Included_JNIScreenShotTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JNIScreenShotTest
 * Method:    captureScreen
 * Signature: (Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_JNIScreenShotTest_captureScreen
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     JNIScreenShotTest
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_JNIScreenShotTest_getNumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
