/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tdkc_udop_screencapture_JNIScreenShot */

#ifndef _Included_com_tdkc_udop_screencapture_JNIScreenShot
#define _Included_com_tdkc_udop_screencapture_JNIScreenShot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tdkc_udop_screencapture_JNIScreenShot
 * Method:    captureScreen
 * Signature: (Ljava/lang/String;IIII)V
 */
JNIEXPORT void JNICALL Java_com_tdkc_udop_screencapture_JNIScreenShot_captureScreen
  (JNIEnv *, jobject, jstring, jint, jint, jint, jint);

/*
 * Class:     com_tdkc_udop_screencapture_JNIScreenShot
 * Method:    getNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_tdkc_udop_screencapture_JNIScreenShot_getNumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
